### ISSUE TITLE
Uzbek Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/uz.reactjs.org#1]
## Maintainer List

* @umidbekk
* @doniyor2109 

## For New Translators

Sahifani tarjima qilish uchun:

1. Checklist ni va quyidagi kommentlardan tarjima qilmoqchi bo'lgan sahifangizni hech kim olmaganini tekshiring.
2. Tarjima qilmoqchi ekanligingiz haqida sahifangiz nomi bilan quyida komment qoldiring. **Iltimos, bir vaqtda faqat bitta sahifani oling.**
3. Repo ni clone qiling, sahigangizni tarjima qiling va pull request yarating.

Hissa qo'shishdan avval quyidagi, texnik va maxsus-React terminlar lug'ati bilan tanishib chiqing.

Agar olgan sahifangizni bundan keyin commit qila olmasligingizni bilib qolsangiz, iltimoz maintainer larni ogohlantirib qo'yishingizni so'raymiz, qaysiki sahifani boshqa birovga tayinlab qo'yishi uchun.

## For Maintainers

Birorta ko'ngilli bo'lganda, ushbu issue ga ko'ngillini username i va PR bilan o'zgartirish kiritib qo'ying. Namuna:

* [ ] Home Page (@username) #1

Qachonki PR merge qilinganda, o'sha sahifani checkbox i tugatilgan sifatida belgilab qo'ying!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@turdiyev) #3
* [ ] Tutorial (@Alisher778)

### Basics

* [x] Hello World (@muhamadamin1992) #31
* [x] Introducing JSX (@zrakhimov) #54
* [x] Rendering Elements (@zrakhimov) #55
* [x] Components and Props (@zrakhimov) #58 
* [x] State and Lifecycle (@MRXDeveloper23) #60
* [ ] Handling Events (@MRXDeveloper23)
* [ ] Conditional Rendering (@shukhratgadoev)
* [x] Lists and Keys (@0tabek16) #63
* [ ] Forms
* [ ] Lifting State Up
* [ ] Composition vs Inheritance
* [ ] Thinking in React

### API Reference

* [ ] React
* [ ] React.Component
* [ ] ReactDOM
* [ ] ReactDOMServer
* [ ] DOM Elements
* [ ] SyntheticEvent
* [ ] Test Utilities
* [ ] Shallow Renderer
* [ ] Test Renderer
* [ ] JS Environment Requirements
* [ ] Glossary

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [ ] tutorial/nav.yml
* [ ] docs/nav.yml

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [ ] Getting Started
* [ ] Add React to a Website
* [ ] Create a New React App
* [x] CDN Links (@dolimovkhumoyun) #43

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [x] Introducing Hooks (@turdiyev) #4
  * [ ] Hooks at a Glance
  * [x] Using the State Hook (@0tabek16)  #32
  * [x] Using the Effect Hook (@0tabek16) #40 
  * [ ] Rules of Hooks
  * [ ] Building Your Own Hooks
  * [ ] Hooks API Reference
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [ ] Accessibility
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries
* [ ] Forwarding Refs
* [ ] Fragments
* [x] Higher-Order Components (@doston92) #44
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals
* [ ] React Without ES6
* [ ] React Without JSX
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [ ] Uncontrolled Components
* [ ] Web Components

### FAQ

* [ ] APIs and AJAX
* [ ] Babel, JSX, and Build Steps
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by avocadowastaken** [comment]
Welcome @turdiyev, @shoyadbek, @doniyor2109, @jaloliddin-kuldoshev, @rustamwin! 
Feel free to talk Uzbek, Russian or English here, I understand everything (mostly). 

For a start I suggest @turdiyev to create a list of tech words with agreed translations for better consistency ([example](https://github.com/reactjs/ru.reactjs.org/blob/master/TRANSLATION.md#%D1%81%D0%BE%D0%B3%D0%BB%D0%B0%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D0%BE-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4%D1%83) from ru.reactjs.org).

**Comment by turdiyev** [comment]
Hi @umidbekkarimov. Okey. I will try to create tech list.

**Comment by turdiyev** [comment]
Home page's all doc files have translated to uzbek. So @umidbekkarimov u can review them.

**Comment by turdiyev** [comment]
Assalomu Alaykum, Akalar tarjimaga aktivniy qo'shilishlaringizni so'rab qolaman. Hech bo'lmasa, **Hooks** bo'limidagi sahifalarni tarjima qilib tashlasak ham zo'r bo'lardi. 

Hozirgacha HomePage ni va HooksIntroductionPage larni qilib bo'ldik. QIlib bo'linganlarni yana bir review qilib chiqsangizlar ham xatolar tuzatilarmidi.

@aurshax, @Shoyadbek, @doniyor2109, @jaloliddin-kuldoshev, @rustamwin.

**Comment by kuldoshev17** [comment]
Assalom aleykum man 'Hooks at a Glance' ni osam boladimi?

**Comment by turdiyev** [comment]
@jaloliddin-kuldoshev aha olavering

**Comment by tesseralis** [comment]
Hey @turdiyev, @umidbekkarimov, @Shoyadbek, how is the translation going? Please let me know if you're having trouble and need help!

**Comment by turdiyev** [comment]
Hello @tesseralis. I'm busy nowadays. But I will try to find time for translation. 

Actually, I'm troubling to find contributors. I did some instructions for junior contriubtors, but I couldn't prepared them properly I think.

**Comment by asadganiev** [comment]
Hello guys @tesseralis and @turdiyev 

I think you got one contributor. 
Tomorrow I will work on translation of following page:
- [ ] Using the State Hook

Have a lovely day.

**Comment by Alisher778** [comment]
Hello, my fellow contributors. I will also try to translate the Tutorials page in my free time.

**Comment by sharopcha** [comment]
> Hello @tesseralis. I'm busy nowadays. But I will try to find time for translation.
> 
> Actually, I'm troubling to find contributors. I did some instructions for junior contriubtors, but I couldn't prepared them properly I think.

Hello everyone. It's nice to see uzbek community here. I am a junior developer and it will be the first time contribution. which page should I take. And also is there anyone to help me to start??

**Comment by turdiyev** [comment]
> Hello, my fellow contributors. I will also try to translate the Tutorials page in my free time.

Assalomu alaykum, Alisher aka. Avvalo Rahmat yordam bermoqchiligingiz uchun. Yuqorida checked bo'lmaganlarni ixtiyoriy birini tanlab boshlasa bo'ladi.

**Comment by turdiyev** [comment]
> > Hello @tesseralis. I'm busy nowadays. But I will try to find time for translation.
> > Actually, I'm troubling to find contributors. I did some instructions for junior contriubtors, but I couldn't prepared them properly I think.
> 
> Hello everyone. It's nice to see uzbek community here. I am a junior developer and it will be the first time contribution. which page should I take. And also is there anyone to help me to start??

Hey @sharopcha. Yuqoridagilarni ixtiyoriy birini olsangiz bo'ladi. Tarjima qilishni boshlaganizni checked qilib qo'yasiz. Yeah, I'll give you instruction

**Comment by turdiyev** [comment]
There is instruction to contribute:
https://github.com/reactjs/uz.reactjs.org/blob/master/TRANSLATION.md#github-open-source-projectga-contribution-qilish-boyicha-qisqa-yoriqnoma

**Comment by Alisher778** [comment]
Can you assign me to "Tutorial" page please?

**Comment by avocadowastaken** [comment]
@Alisher778 done

**Comment by jkhusanov** [comment]
Hey everyone, thank you for starting this ambitious project! Before we dive right into translations would not it be better if we first add some terminology like in these translations: [az](https://github.com/reactjs/az.reactjs.org/blob/master/glossary.md) and [ru](https://github.com/reactjs/ru.reactjs.org/blob/master/TRANSLATION.md)? That would help out new contributors and unify our terminology dictionary. 

**_Update:_** 
Looks like we already have a [file](https://github.com/reactjs/uz.reactjs.org/blob/master/TRANSLATION.md) set up with main rules and terminology. It would be great if we added a link to that file in the lines above:

> Hissa qo'shishdan avval quyidagi, texnik va maxsus-React terminlar lug'ati bilan tanishib chiqing.

Of course, we could always update that file so it's up to date and more clear. 

Also, have a first PR with a hotfix https://github.com/reactjs/uz.reactjs.org/pull/29. Thank you 😊 🙌

**Comment by jkhusanov** [comment]
@umidbekkarimov thank you for approving my PR! I feel like I could start contributing to the project more. If you guys need some help, I would love to join the maintainer's list. Although we all are busy with work and other things, at least I could help out with some PR reviews. I was recently inspired by @tesseralis presentation at React Conf, where I saw the Uzbek language in the slides :)

**Comment by avocadowastaken** [comment]
Hello @jkhusanov, once again - thanks for your help! There is not much activity here, so it would be great to receive some contribution!

**Comment by muhamadamin1992** [comment]
Assalomu aleykum manam bo'sh vaqtda tarjimaga hissa qo'shmoqchi edim Hello worldni tarjima qimoqchiman

**Comment by 0tabek16** [comment]
Could anyone please assignme to "Using the State Hook"?

**Comment by avocadowastaken** [comment]
@0tabek16 done!

**Comment by 0tabek16** [comment]
Could anyone have a look at my PR https://github.com/reactjs/uz.reactjs.org/pull/32

**Comment by 0tabek16** [comment]
Now can translate "Using the Effect Hook". Please, assign me :)

**Comment by avocadowastaken** [comment]
@0tabek16 here you go!

**Comment by Mamirjanoff** [comment]
Assalomu aleykum hormanglar tezroq tarjima qilsangizlar yahshi bo'lar edi) vaqt bölganda ruschadan uzbekchaga yordam qilishim mumkin lekin gitni yahshi örganganim yöq hali tushunmayabman((

**Comment by 0tabek16** [comment]
I can start translating "Building Your Own Hooks"

**Comment by dolimovkhumoyun** [comment]
Assalomu alaykum. Men, **CDN Links** sahifasini tarjima qilmoqchi edim. Shu sahifani menga biriktirib qo'ya olasizlarmi? @umidbekkarimov

**Comment by avocadowastaken** [comment]
@dolimovkhumoyun hello! feel free to create a PR!

**Comment by ghost** [comment]
Assalomu alaykum, men "Introducing JSX"ni tarjima qilmoqchidim. Telegramdayam gruppa bormi? Tushunmagan savollar bo'lsa, github'dan ko'ra Telegramda tezroq javob olardik

**Comment by AmirovQodir** [comment]
Assalomu alaykum. Tarjima ishlari davom etayabdimi hali ham? Men ham qo'shilmoqchi edim.

**Comment by khurmatillo23** [comment]
@umidbekk  Hi can you assign me the "State and Lifecycle" page?

**Comment by doniyor2109** [comment]
@MRXDeveloper23 Done

**Comment by khurmatillo23** [comment]
@doniyor2109 Hi can you check out PR and now I can translate the "Handling events" page please assign me

**Comment by noonosh** [comment]
Are u still alive here? Almost a month of last merged PR and 12/88 not completed tasks... If the work is still up, I can help to translate any page that is the first priority (:

**Comment by OtabekVaxobov** [comment]
ooo!

**Comment by qrbazamat** [comment]
hgh

**Comment by 0tabek16** [comment]
Salom akalar :) React jamoasi yangi yoʻriqnomani (documentation) e'lon qilishdi... shu yangi yoʻriqnomani qanday tarjima qilsak boʻladi?

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now very outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
